__title__ = "BoaBoard"
__description__ = "BoaBoard is a modern, Python-powered attendance dashboard designed to streamline employee tracking and provide real-time insights with a sleek and intuitive interface."
__version__ = "0.1.0"
__author__ = "Julius Koenig"
__author_email__ = "info@bastelquartier.de"
__license__ = "GPL-3.0"
